# Generated by Django 5.1.1 on 2025-01-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='0ee9a0fc-28bd-44ec-881b-4fca4acb4929', on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todo.category'),
            preserve_default=False,
        ),
    ]
