# Generated by Django 5.1.1 on 2025-03-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=12, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
