# Generated by Django 5.1.1 on 2025-03-23 06:16

import todo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(validators=[todo.validators.CustomValidators.text_minimal, todo.validators.CustomValidators.text_maximal]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[todo.validators.CustomValidators.text_minimal, todo.validators.CustomValidators.text_maximal]),
        ),
    ]
